name: Preview docs
on:
  pull_request:
    paths-ignore:
      - wiki/**
      - .github/**
      - "!.github/workflows/preview-docs.yml"
      - .gitignore
      - LICENSE
      - README.md
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true
jobs:
  preview-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: npm
      - uses: jcbhmr/setup-rust-action@v1
      - run: sudo apt-get update && sudo apt-get install libgtk-3-dev
      - run: npm ci
      - run: npm run build:docs
      - uses: actions/upload-artifact@v3
        with:
          name: preview-docs
          path: docs/dist
